### ISSUE TITLE
Tìm hiểu về công nghệ Kubernetes và ứng dụng của nó trong Docker.

### ISSUE THREAD

**Issue by tienduc18** [tienduc18/Project_CP_Kubernetes#14]

**Comment by tienduc18** [comment]
[Cloud_Computing_DeTai1.pdf](https://github.com/tienduc18/Project_CP_Kubernetes/files/6377204/Cloud_Computing_DeTai1.pdf)

**Comment by la0156** [comment]
[Cloud_Computing_DeTai1.pdf](https://github.com/tienduc18/Project_CP_Kubernetes/files/6396781/Cloud_Computing_DeTai1.pdf)

**Comment by la0156** [comment]
cập nhật xong rồi nhé

**Comment by tienduc18** [comment]
Okay để tôi check

**Comment by tienduc18** [comment]
Chú ý một số từ vựng tiếng Anh còn chưa được dịch kỹ từ trang số 16 trở về sau nhé.

**Comment by tienduc18** [comment]
Đã cập nhật một số lỗi chính tả và điều chỉnh đại từ xưng hô
[18133007_TranTienDuc_TimHieu_Kubernetes.docx](https://github.com/tienduc18/Project_CP_Kubernetes/files/6564976/18133007_TranTienDuc_TimHieu_Kubernetes.docx)
[18133007_TranTienDuc_TimHieu_Kubernetes.pdf](https://github.com/tienduc18/Project_CP_Kubernetes/files/6565009/18133007_TranTienDuc_TimHieu_Kubernetes.pdf)

**Comment by tienduc18** [comment]
Cập nhật trang bìa và các đề mục mới về hướng dẫn sử dụng, vấn đề còn tồn tại và hướng phát triển trong tương lai.
[18133007_TranTienDuc_TimHieu_Kubernetes.pdf](https://github.com/tienduc18/Project_CP_Kubernetes/files/6565053/18133007_TranTienDuc_TimHieu_Kubernetes.pdf)
[18133007_TranTienDuc_TimHieu_Kubernetes.docx](https://github.com/tienduc18/Project_CP_Kubernetes/files/6565054/18133007_TranTienDuc_TimHieu_Kubernetes.docx)

**Comment by tienduc18** [comment]
Cần bổ sung phần hướng phát triển trong tương lai.
[18133007_TranTienDuc_TimHieu_Kubernetes.pdf](https://github.com/tienduc18/Project_CP_Kubernetes/files/6565283/18133007_TranTienDuc_TimHieu_Kubernetes.pdf)
[18133007_TranTienDuc_TimHieu_Kubernetes.docx](https://github.com/tienduc18/Project_CP_Kubernetes/files/6565284/18133007_TranTienDuc_TimHieu_Kubernetes.docx)

**Comment by tienduc18** [comment]
Cập nhật lại tên file.
[CloudComputing_DeTai1.pdf](https://github.com/tienduc18/Project_CP_Kubernetes/files/6565792/CloudComputing_DeTai1.pdf)
[CloudComputing_DeTai1.docx](https://github.com/tienduc18/Project_CP_Kubernetes/files/6565793/CloudComputing_DeTai1.docx)

**Comment by la0156** [comment]
Tôi đã thêm và đọc lại rồi thấy oke rồi đó
[Điện toán đám mây ppt Thuyết trình.pptx](https://github.com/tienduc18/Project_CP_Kubernetes/files/6566387/Di.n.toan.dam.may.ppt.Thuy.t.trinh.pptx)

[CloudComputing_DeTai1.docx](https://github.com/tienduc18/Project_CP_Kubernetes/files/6566389/CloudComputing_DeTai1.docx)

**Comment by tienduc18** [comment]
Cập nhật nội dung dễ hiểu hơn cho người đọc.
[CloudComputing_DeTai1.pdf](https://github.com/tienduc18/Project_CP_Kubernetes/files/6566658/CloudComputing_DeTai1.pdf)
[CloudComputing_DeTai1.docx](https://github.com/tienduc18/Project_CP_Kubernetes/files/6566659/CloudComputing_DeTai1.docx)

**Comment by la0156** [comment]
[Uploading Điện toán đám mây ppt Thuyết trình.pptx…]()

**Comment by la0156** [comment]
[Điện toán đám mây ppt Thuyết trình.pptx](https://github.com/tienduc18/Project_CP_Kubernetes/files/6566671/Di.n.toan.dam.may.ppt.Thuy.t.trinh.pptx)

**Comment by tienduc18** [comment]
Đã cập nhật nội dung của các file báo cáo cần nộp.
[Nhom1_CloudComputing_DeTai1.pdf](https://github.com/tienduc18/Project_CP_Kubernetes/files/6566713/Nhom1_CloudComputing_DeTai1.pdf)
[Nhom1_CloudComputing_DeTai1_ThuyetTrinh.pptx](https://github.com/tienduc18/Project_CP_Kubernetes/files/6566715/Nhom1_CloudComputing_DeTai1_ThuyetTrinh.pptx)
[Nhom1_CloudComputing_DeTai1.docx](https://github.com/tienduc18/Project_CP_Kubernetes/files/6566716/Nhom1_CloudComputing_DeTai1.docx)

**Comment by tienduc18** [comment]
Cập nhật lần cuối (Đã bổ sung link github vào file docx)
[Nhom1_CloudComputing_DeTai1.docx](https://github.com/tienduc18/Project_CP_Kubernetes/files/6609029/Nhom1_CloudComputing_DeTai1.docx)
[Nhom1_CloudComputing_DeTai1.pdf](https://github.com/tienduc18/Project_CP_Kubernetes/files/6609028/Nhom1_CloudComputing_DeTai1.pdf)
